language: node_js
sudo: required
node_js: 0.10
services: mongodb
script: make travis
after_script: make report
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
